s4tools, starting moving to ldb call only

diff --git a/modules/samba/files/s4classcheck b/modules/samba/files/s4classcheck
--- a/modules/samba/files/s4classcheck
+++ b/modules/samba/files/s4classcheck
@@ -68,94 +68,84 @@ if [ $# -gt 1 ]; then
 fi
 
 # get class name #
-if [ ! -z "$1" ]; then
-   className="$1"
-fi
+className="$1"
 
 # check the class group #
 if [ ! -z "$classGroup" ]; then
    classGroup=${classGroup,,}
-fi
-
-# if the class name is not set #
-# try to find it with the group #
-if [ -z "$className" ]; then
-
-   searchCond=''
-
-   if [ ! -z "$classGroup" ]; then
-      searchCond="${searchCond}(cn=$classGroup)"
-   fi
-
-   if [ ! -z "$classShowName" ]; then
-      searchCond="${searchCond}(displayName=$classShowName)"
-   fi
-
-   if [ -z "$searchCond" ]; then
-      usage
-   fi
-
-   searchCond="(&(objectClass=group)${searchCond})"
-
-   searchClass=''
-   searchClass=$(s4ldbsearch -H $samDatabase -b $baseUserDN,$baseDN $searchCond dn | grep '^dn: ')
-   if [ -z "$searchClass" ]; then
-      echo "No class found !"
-      exit 1
-   else
-      resultCount=$(echo "$searchClass" | wc -l)
-      if [ "$resultCount" -ne "1" ]; then
-         echo "Multiple classes found !"
+   if [ ! -z "$className" ]; then
+      if [ "${className,,}" != "$classGroup" ]; then
+         echo "Error : The class group must be the class name in lowercase !"
          exit 1
       fi
-
-      # read the class name  #
-      # the OU containing the group #
-      # (no need to remove the dn: part as we use -f2 ) #
-      className=$(echo "$searchClass" | cut -d, -f2)
-      className=${className#OU=}
    fi
 fi
 
+########################
+# find the class group #
+########################
 
-# get the class group #
-if [ -z "$classGroup" ]; then
+# get the group name if possible
+if [ ! -z "$className" ]; then
    classGroup=${className,,}
 fi
 
-# search the class OU and the group #
-searchCond="(cn=$classGroup)"
-if [ ! -z "$classShowName" ]; then
-   searchCond="${searchCond}(displayName=$classShowName)"
+# build search cond #
+if [ ! -z "$classGroup" ]; then
+   searchCond="(cn=$classGroup)"
 fi
-searchCond="(&(objectClass=group)${searchCond})"
 
-searchClass=''
-searchClass=$(s4ldbsearch -H $samDatabase -b $baseUserDN,$baseDN $searchCond  dn | grep "^dn: CN=$classGroup,OU=$className")
+if [ ! -z "$classShowName" ]; then
+   if [ -z "$searchCond" ]; then
+      searchCond="(displayName=$classShowName)"
+   else
+      searchCond="(&${searchCond}(displayName=$classShowName)"
+   fi
+fi
 
-if [ -z "$searchClass" ]; then
-   echo "The class cannot be found !"
+# check search cond #
+if [ -z "$searchCond" ]; then
+   usage
+fi
+
+# search #
+searchClass=$(s4ldbsearch $baseUserDN,$baseDN sub group $searchCond)
+if [ "$?" -ne "0" ]; then
+   echo "No class found !"
    exit 1
 else
-
-   # check the corresponding share OU #
-   classDN=${searchClass#dn: CN=$classGroup,}
-   classDN=${classDN%,$baseDN}
-   classShareDN=${classDN%$baseUserDN}
-   classShareDN="${classShareDN}$baseShareDN"
-
-   OUName=$(echo "$classShareDN" | cut -d, -f1)
-   OUName=${OUName#OU=}
-
-   searchCond="(&(objectClass=organizationalUnit)(ou=$OUName))"
-   searchClass=''
-   searchClass=$(s4ldbsearch -H $samDatabase -b $classShareDN,$baseDN $searchCond  dn | grep "^dn: ")
-
-   if [ -z "$searchClass" ]; then
-      echo "Cannot found the share OU of the class $className !"
-      exit 1
+   resultCount=$(echo "$searchClass" | wc -l)
+   if [ "$resultCount" -ne "1" ]; then
+      echo "Multiple classes found !"
    fi
+fi
 
+# rebuild the class name/group if needed #
+if [ -z "$className" ]; then
+
+   # read the class name  #
+   # the OU containing the group #
+   # (no need to remove the dn: part as we use -f2 ) #
+   className=$(echo "$searchClass" | cut -d, -f2)
+   className=${className#OU=}
+   classGroup=${className,,}
+fi
+
+
+######################
+# check the share dn #
+######################
+
+# check the corresponding share OU #
+classDN=${searchClass#CN=$classGroup,}
+classDN=${classDN%,$baseDN}
+classShareDN=${classDN%$baseUserDN}
+classShareDN="${classShareDN}$baseShareDN"
+
+searchClass=$(s4ldbsearch $classShareDN,$baseDN base ou '()')
+if [ "$?" -ne "0" ]; then
+   echo "Cannot found the share OU of the class $className ! Maybe not a class group."
+   exit 1
 fi
 
 echo "Class Name: $className"
diff --git a/modules/samba/files/s4shareadd b/modules/samba/files/s4shareadd
--- a/modules/samba/files/s4shareadd
+++ b/modules/samba/files/s4shareadd
@@ -153,7 +153,7 @@ shareClassGroup=${shareClassGroup#Class group: }
 shareName="${shareClassGroup}.${1,,}"
 
 # check if the share already exist #
-if wbinfo --user-info $shareName > /dev/null 2>&1; then
+if s4ldbsearch $baseShareDN,$baseDN sub user "(cn=$shareName)" > /dev/null; then
    echo "The share $shareName already exist !"
    exit 1
 fi
@@ -193,8 +193,7 @@ fi
 
 # check owner user #
 if [ "$shareOwnerUser" != "root" ]; then
-   struid=$(wbinfo --user-info="$shareOwnerUser")
-   if [ $? -ne 0 ]; then
+   if ! s4ldbsearch $baseDN sub user "(cn=$shareOwnerUser)" > /dev/null; then
       echo "User $shareOwnerUser not found !"
       exit 1
    fi
@@ -202,11 +201,10 @@ fi
 
 # check owner group #
 if [ "$shareOwnerGroup" != "root" ]; then
-   strgid=$(wbinfo --group-info="$shareOwnerGroup")
-   if [ $? -ne 0 ]; then
-     echo "Group $shareOwnerGroup not found !"
-     exit 1
-  fi
+   if ! s4ldbsearch $baseDN sub group "(cn=$shareOwnerGroup)" > /dev/null; then
+      echo "Group $shareOwnerGroup not found !"
+      exit 1
+   fi
 fi
 
 
@@ -230,16 +228,16 @@ fi
 ###############################
 
 # get the new uid #
-userUid=$(s4ldbsearch -H $samDatabase -s base -b CN=$shortDomain,CN=ypservers,CN=ypServ30,CN=RpcServices,CN=System,$baseDN msSFU30MaxUidNumber | grep 'msSFU30MaxUidNumber:')
+userUid=$(s4ldbsearch CN=$shortDomain,CN=ypservers,CN=ypServ30,CN=RpcServices,CN=System,$baseDN base all '()' msSFU30MaxUidNumber | cut -f2)
 if [ -z "$userUid" ]; then
    userUid="$baseUid"
-else
-   userUid=$(echo $userUid | sed 's/^msSFU30MaxUidNumber: \(.*\)/\1/')
 fi
 
 # get the gid #
-strgid=$(wbinfo --group-info="$shareClassGroup")
-userGid=$(echo $strgid | cut -d ":" -f 3)
+shareClassGroupDN=$(echo "$shareClassInfo" | grep '^Class DN: ')
+shareClassGroupDN=${shareClassDN#Class DN: }
+strgid=$(s4ldbsearch CN=$shareClassGroup,$shareClassGroupDN,$baseDN base group '()' gidNumber)
+userGid=$(echo $strgid | cut -f2)
 
 
 #################
@@ -277,10 +275,10 @@ ldbmodify --url=$samDatabase -b $baseDN /tmp/$shareName
 rm /tmp/$shareName
 
 
-######################
-# associate the share
-# with the show classes
-######################
+#########################
+# associate the share   #
+# with the show classes #
+#########################
 IFS=','
 for shareShowClass in $shareShowClasses; do
    samba-tool group addmembers ${shareShowClass,,} $shareName
@@ -288,9 +286,9 @@ done
 unset IFS
 
 
-############
-# ok
-############
+#######
+# ok  #
+#######
 echo "Share created on AD !"
 echo "##################################################"
 echo "# !!! Launch s4makeshareddirs on the servers !!! #"
diff --git a/modules/samba/files/s4sharedel b/modules/samba/files/s4sharedel
--- a/modules/samba/files/s4sharedel
+++ b/modules/samba/files/s4sharedel
@@ -77,9 +77,8 @@ fi
 shareName=$1
 
 # check that the user is a share #
-searchShare=$(s4ldbsearch -H $samDatabase -b $baseShareDN,$baseDN "(cn=$shareName)" dn | grep "dn: CN=$shareName,.*$baseShareDN")
-if [ -z "$searchShare" ]; then
-   echo "Connot find the share $shareName !"
+if ! s4ldbsearch $baseShareDN,$baseDN sub user "(cn=$shareName)" > /dev/null; then
+   echo "Cannot find the share $shareName !"
    exit 0
 fi
 
