s4tools : removed windbind dependency and moved to perl

diff --git a/modules/samba/files/s4classcheck b/modules/samba/files/s4classcheck
--- a/modules/samba/files/s4classcheck
+++ b/modules/samba/files/s4classcheck
@@ -99,12 +99,14 @@ if [ ! -z "$classShowName" ]; then
    if [ -z "$searchCond" ]; then
       searchCond="(displayName=$classShowName)"
    else
-      searchCond="(&${searchCond}(displayName=$classShowName)"
+      searchCond="(&${searchCond}(displayName=$classShowName))"
    fi
 fi
 
 # check search cond #
 if [ -z "$searchCond" ]; then
+
+   # no condition given #
    usage
 fi
 
@@ -117,6 +119,7 @@ else
    resultCount=$(echo "$searchClass" | wc -l)
    if [ "$resultCount" -ne "1" ]; then
       echo "Multiple classes found !"
+      exit 1
    fi
 fi
 
@@ -125,7 +128,6 @@ if [ -z "$className" ]; then
 
    # read the class name  #
    # the OU containing the group #
-   # (no need to remove the dn: part as we use -f2 ) #
    className=$(echo "$searchClass" | cut -d, -f2)
    className=${className#OU=}
    classGroup=${className,,}
@@ -144,7 +146,7 @@ classShareDN="${classShareDN}$baseShareDN"
 
 searchClass=$(s4ldbsearch $classShareDN,$baseDN base ou '()')
 if [ "$?" -ne "0" ]; then
-   echo "Cannot found the share OU of the class $className ! Maybe not a class group."
+   echo "Cannot find the share OU of the class $className ! Maybe not a class group."
    exit 1
 fi
 
@@ -154,5 +156,3 @@ echo "Class DN: $classDN"
 echo "Class share DN: $classShareDN"
 
 exit 0
-
-
diff --git a/modules/samba/files/s4studentmove b/modules/samba/files/s4studentmove
--- a/modules/samba/files/s4studentmove
+++ b/modules/samba/files/s4studentmove
@@ -65,19 +65,16 @@ fi
 studentName=$1
 studentTargetClassName=$2
 
-# check if the student account exist #
-# already done in s4usermove #
-
 # check if the account is a student #
 if ! s4ldbsearch $baseStudentDN,$baseDN sub user "(cn=$studentName)" > /dev/null; then
    echo "The user $studentName is not a student !"
-   exit 0
+   exit 1
 fi
 
 # check if the class exist #
 if ! studentTargetClassInfo=$(s4classcheck $studentTargetClassName); then
-   echo "The student class $studentTargetClassName cannot be found !"
-   exit 0
+   echo "The class $studentTargetClassName cannot be found !"
+   exit 1
 fi
 
 # check if the target class is a student's class #
@@ -85,7 +82,7 @@ studentTargetClassDN=$(echo "$studentTargetClassInfo" | grep '^Class DN: ')
 studentTargetClassDN=${studentTargetClassDN#Class DN: }
 if ! echo "$studentTargetClassDN" | grep -q "$baseStudentDN\$"; then
    echo "The student class $studentTargetClassName is not a student class !"
-   exit 0
+   exit 1
 fi
 
 ####################
@@ -93,5 +90,3 @@ fi
 ####################
 
 s4usermove $studentName $studentTargetClassName
-
-
