improved s4 scripts

diff --git a/modules/samba/files/s4classadd b/modules/samba/files/s4classadd
--- a/modules/samba/files/s4classadd
+++ b/modules/samba/files/s4classadd
@@ -8,7 +8,8 @@ source /etc/samba/s4.conf
 # usage #
 function usage()
 {
-    echo "usage: $0 <class_name> [-b base_class] [-d display_name]"
+    binName=$(basename $0)
+    echo "usage: $binName <class_name> [-b base_class] [-d display_name]"
     exit 0
 }
 
@@ -69,11 +70,19 @@ classGroup=${1,,}
 
 # check the base class #
 if [ -z "$baseClass" ]; then
-   baseClassName=${baseUserDN#OU=}
    baseClassGroup=${baseUserGroup}
 else
    baseClassName=${baseClass}
-   baseClassGroup=${baseClass,,}
+   if ! baseClassInfo=$(s4classcheck $baseClassName); then
+      echo "The base class $baseClassName cannot be found !"
+      exit 1
+   else
+      baseClassGroup=$(echo "$baseClassInfo" | grep 'Class group: ')
+      baseClassGroup=${baseClassGroup#Class group: }
+      baseClassDN=$(echo "$baseClassInfo" | grep 'Class DN: ')
+      baseClassDN=${baseClassDN#Class DN: }
+      baseClassDN=${baseClassDN%${baseUserDN}}
+   fi
 fi
 
 # check display name #
@@ -87,36 +96,14 @@ fi
 
 # check if the class already exist #
 if wbinfo --group-info=$classGroup > /dev/null 2>&1; then
-   echo "The class $classGroupName already exist !"
+   echo "The class $className already exist !"
    exit 0
 fi
-
-# search for the base class #
-searchClass=$(s4ldbsearch -H $samDatabase -b $baseUserDN,$baseDN "(cn=$baseClassGroup)" | grep "dn: CN=$baseClassGroup,OU=$baseClassName")
-if [ -z "$searchClass" ]; then
-   echo "The base class $baseClassName cannot be found !"
-   exit 0
-else
-   baseClassDN=${searchClass#dn: CN=$baseClassGroup,}
-   baseClassDN=${baseClassDN%$baseUserDN,$baseDN}
-fi
-
 
 # create the organizational unit #
 echo "create $className organizational units."
-echo "dn: OU=${className},${baseClassDN}${baseUserDN},${baseDN}
-changetype: add
-objectClass: top
-objectClass: organizationalunit
-
-dn: OU=${className},${baseClassDN}${baseShareDN},${baseDN}
-changetype: add
-objectClass: top
-objectClass: organizationalunit" > /tmp/$className
-
-ldbmodify --url=$samDatabase -b $baseDN /tmp/$className
-rm /tmp/$className
-
+samba-tool ou create "OU=${className},${baseClassDN}${baseUserDN},${baseDN}"
+samba-tool ou create "OU=${className},${baseClassDN}${baseShareDN},${baseDN}"
 
 # create the groups #
 s4groupadd $classGroup -d OU=${className},${baseClassDN}${baseUserDN}
@@ -128,4 +115,3 @@ displayName: $classDisplayName" > /tmp/$className
 
 ldbmodify --url=$samDatabase -b $baseDN /tmp/$className
 rm /tmp/$className
-
diff --git a/modules/samba/files/s4shareadd b/modules/samba/files/s4shareadd
--- a/modules/samba/files/s4shareadd
+++ b/modules/samba/files/s4shareadd
@@ -8,8 +8,9 @@ source /etc/samba/s4.conf
 # usage #
 function usage()
 {
-    echo "usage: $0 <share_name> <mod,acls> [share_class] [-o owner] [-c show_classes] [-n show_name] [-s server]"
-    exit 0
+    binName=$(basename $0)
+    echo "usage: $binName <share_name> <[primary_access_class:]access_class1,access_class2, ...> [[mod,]acls] [-o owner] [-n show_name] [-s server]"
+    exit 1
 }
 
 
@@ -20,13 +21,10 @@ while [[ -n "$@" ]]; do
 
     # test option #
     OPTIND=1
-    while getopts ":ho:c:n:s:" opt; do
+    while getopts ":ho:n:s:" opt; do
 	case $opt in
 	    o)
 		shareOwner=$OPTARG
-		;;
-	    c)
-		shareShowClasses=$OPTARG
 		;;
             n)
                 shareShowName=$OPTARG
@@ -43,7 +41,7 @@ while [[ -n "$@" ]]; do
 		;;
 	    :)
 		echo "parameter of -$OPTARG not specified !"
-		exit 0
+		exit 1
 		;;
 	esac
     done
@@ -67,98 +65,161 @@ fi
 # analyse args
 #################
 
+#-------------------#
+# check args number #
+#-------------------#
+
 # max three args #
 if [ $# -gt 3 ] || [ $# -lt 2 ]; then
     usage
 fi
 
-#  check share's class #
-if [ -z "$3" ]; then
-   shareClassName=${baseUserDN#OU=}
-   shareClassGroup=${baseUserGroup}
-else
-   shareClassName=$3
-   shareClassGroup=${3,,}
+
+#-----------------------------#
+# check arg2 : access classes #
+#-----------------------------#
+
+# get share classes #
+shareShowClasses="$2"
+
+if echo "$shareShowClasses" | grep -q ':'; then
+   primaryShareShowClass=$(echo "$shareShowClasses" | cut -d: -f1)
 fi
 
-# parse share name  #
-shareName="${shareClassGroup}.${1,,}"
+if [ ! -z "$primaryShareShowClass" ]; then
+   shareShowClasses="${primaryShareShowClass},${shareShowClasses#${primaryShareShowClass}:}"
+fi
 
+
+# check all the classes      #
+# and compute the base class #
+IFS=','
+for shareShowClass in $shareShowClasses; do
+
+   if ! classInfo=$(s4classcheck $shareShowClass); then
+      echo "Class $shareShowClass cannot be found !"
+      exit 1
+   fi
+
+   classDN=$(echo "$classInfo" | grep 'Class DN: ')
+   classDN=${classDN#Class DN: }
+   classDN=$(echo "$classDN" | rev)
+   if [ -z "$commonDN" ]; then
+      commonDN="$classDN"
+      firstShareClassInfo="$classInfo"
+   else
+      fieldPos="2"
+      commonPart=$(echo "$commonDN" | cut -d, -f1) # the root is always common
+      nextField=$(echo "$commonDN" | cut -d, -f2)
+      while [ ! -z "$nextField" ] && echo "$classDN" | grep -q "^$commonPart,$nextField"; do
+         fieldPos=$((fieldPos+1))
+         commonPart="$commonPart,$nextField"
+         nextField=$(echo "$commonDN" | cut -d, -f${fieldPos})
+      done
+      commonDN="$commonPart"
+   fi
+done
+unset IFS
+commonDN=$(echo "$commonDN" | rev)
+
+# get base class, check and get info #
+shareBaseClass=$(echo "$commonDN" | cut -d, -f1)
+shareBaseClass=${shareBaseClass#OU=}
+if ! shareBaseClassInfo=$(s4classcheck $shareBaseClass); then
+   echo "Error : cannot found a correct common base class !"
+   exit 1
+fi
+
+# choose the primary class #
+if [ -z "$primaryShareShowClass" ]; then
+   # no primary class, use the common base class #
+   shareClassInfo="$shareBaseClassInfo"
+else
+   # use primary class, the first in the list #
+   shareClassInfo="$firstShareClassInfo"
+fi
+
+shareClass=$(echo "$shareClassInfo" | grep 'Class Name: ')
+shareClass=${shareClass#Class Name: }
+
+
+#--------------------------#
+# check arg1 : share name  #
+#--------------------------#
+
+# build the final share name : group.shareName #
+shareClassGroup=$(echo "$shareClassInfo" | grep 'Class group: ')
+shareClassGroup=${shareClassGroup#Class group: }
+shareName="${shareClassGroup}.${1,,}"
 
 # check if the share already exist #
 if wbinfo --user-info $shareName > /dev/null 2>&1; then
-   echo "The share already exist !"
-   exit 0
+   echo "The share $shareName already exist !"
+   exit 1
 fi
 
 
-# search the class #
-searchClass=$(s4ldbsearch -H $samDatabase -b $baseUserDN,$baseDN "(cn=$shareClassGroup)" | grep "dn: CN=$shareClassGroup,OU=$shareClassName")
-if [ -z "$searchClass" ]; then
-   echo "The class $shareClassName cannot be found !"
-   exit 0
+#-----------------------------#
+# check arg3 : mod,acls       #
+#-----------------------------#
+sharePermissions=$3
+if [ -z "$sharePermissions" ]; then
+   sharePermissions="0550"
 else
-   shareClassDN=${searchClass#dn: CN=$shareClassGroup,}
-   shareClassDN=${shareClassDN%$baseUserDN,$baseDN}
+   # check mod #
+   sharePermissionsMod=$(echo "$sharePermissions" | cut -d, -f1)
+   if ! echo "$sharePermissionsMod" | grep -q -E '[0-2]?[0-7][0-7][0-7]'; then
+      sharePermissions="0555,$sharePermissions"
+   fi
 fi
 
 
-# save permissions #
-sharePermissions=$2
+#------------------#
+# check -o : owner #
+#------------------#
+shareBaseClassGroup=$(echo "$shareBaseClassInfo" | grep 'Class group: ')
+shareBaseClassGroup=${shareBaseClassGroup#Class group: }
 
-# check owner #
 if [ -z "$shareOwner" ]; then
-   shareOwner="root:${shareClassGroup}"
+   shareOwner="root:${shareBaseClassGroup}"
 fi
 
 shareOwnerUser=$(echo $shareOwner | cut -d: -f1)
 shareOwnerGroup=$(echo $shareOwner | cut -d: -f2)
 if [ -z "$shareOwnerUser" ] || [ -z "$shareOwnerGroup" ]; then
    echo "Cannot parse owner : $shareOwner"
-   exit 0
+   exit 1
 fi
 
-if [ "$shareOwnerUser" == "root" ]; then
-   shareOwnerUID="0"
-else
+# check owner user #
+if [ "$shareOwnerUser" != "root" ]; then
    struid=$(wbinfo --user-info="$shareOwnerUser")
    if [ $? -ne 0 ]; then
       echo "User $shareOwnerUser not found !"
-      exit 0
+      exit 1
    fi
-   shareOwnerUID=$(echo $struid | cut -d ":" -f 3)
 fi
 
-strgid=$(wbinfo --group-info="$shareOwnerGroup")
-if [ $? -ne 0 ]; then
-   echo "Group $shareOwnerGroup not found !"
-   exit 0
-fi
-shareOwnerGID=$(echo $struid | cut -d ":" -f 3)
-
-
-# check show classes #
-if [ -z "$shareShowClasses" ]; then
-   shareShowClasses="$shareClassName"
-fi
-
-IFS=','
-for shareShowClass in $shareShowClasses; do
-   wbinfo --group-info ${shareShowClass,,} > /dev/null 2>&1
+# check owner group #
+if [ "$shareOwnerGroup" != "root" ]; then
+   strgid=$(wbinfo --group-info="$shareOwnerGroup")
    if [ $? -ne 0 ]; then
-      echo "Class $shareShowClass cannot be found !"
-      exit 0
-   fi
-done
-unset IFS
-
-# check show name #
-if [ -z "$shareShowName" ]; then
-   shareShowName=${1,,}
+     echo "Group $shareOwnerGroup not found !"
+     exit 1
+  fi
 fi
 
 
-# check the server #
+#----------------------#
+# check -n : show name #
+#----------------------#
+if [ -z "$shareShowName" ]; then
+   shareShowName="$1"
+fi
+
+#-------------------#
+# check -s : server #
+#-------------------#
 if [ -z "$shareServer" ]; then
    shareServer=$(hostname)
 fi
@@ -177,7 +238,7 @@ else
 fi
 
 # get the gid #
-strgid=$(wbinfo --group-info="$baseShareGroup")
+strgid=$(wbinfo --group-info="$shareClassGroup")
 userGid=$(echo $strgid | cut -d ":" -f 3)
 
 
@@ -186,8 +247,11 @@ userGid=$(echo $strgid | cut -d ":" -f 3)
 #################
 echo "Creating s4 share $shareName"
 
+shareClassDN=$(echo "$shareClassInfo" | grep 'Class share DN: ')
+shareClassDN=${shareClassDN#Class share DN: }
+
 # create the share #
-samba-tool user create $shareName --userou=${shareClassDN}${baseShareDN} --random-password \
+samba-tool user create $shareName --userou=${shareClassDN} --random-password \
 --use-username-as-cn \
 --given-name="$shareShowName" \
 --description="${shareOwner},${sharePermissions}" \
diff --git a/modules/samba/files/s4studentadd b/modules/samba/files/s4studentadd
--- a/modules/samba/files/s4studentadd
+++ b/modules/samba/files/s4studentadd
@@ -8,7 +8,8 @@ source /etc/samba/s4.conf
 # usage #
 function usage()
 {
-    echo "usage: $0 <student_name> <student_class> [-s server] [-p passwd]"
+    binName=$(basename $0)
+    echo "usage: $binName <student_name> <student_class> [-s server] [-p passwd]"
     exit 0
 }
 
@@ -70,9 +71,15 @@ newStudentClass=$2
 newStudentOptions=""
 
 # check if the class exist #
-newStudentClassGroup=${newStudentClass,,}
-searchClass=$(s4ldbsearch -H $samDatabase -b $baseStudentDN,$baseDN "(cn=$newStudentClassGroup)" | grep "dn: CN=$newStudentClassGroup,OU=$newStudentClass,$baseStudentDN")
-if [ -z "$searchClass" ]; then
+if ! newStudentClassInfo=$(s4classcheck $newStudentClass); then
+   echo "The student class $newStudentClass cannot be found !"
+   exit 0
+fi
+
+# check if the class is a student class #
+newStudentClassDN=$(echo "$newStudentClassInfo" | grep 'Class DN: ')
+newStudentClassDN=${newStudentClassDN#Class DN: }
+if ! echo "$newStudentClassDN" | grep -q "$baseStudentDN\$"; then
    echo "The student class $newStudentClass cannot be found !"
    exit 0
 fi
@@ -89,5 +96,4 @@ fi
 ######################
 # create the Student #
 ######################
-
 s4useradd $newStudentName $newStudentClass $newStudentOptions
diff --git a/modules/samba/files/s4studentmove b/modules/samba/files/s4studentmove
--- a/modules/samba/files/s4studentmove
+++ b/modules/samba/files/s4studentmove
@@ -8,7 +8,8 @@ source /etc/samba/s4.conf
 # usage #
 function usage()
 {
-    echo "usage: $0 <student_name> <target_class>"
+    binName=$(basename $0)
+    echo "usage: $binName <student_name> <target_class>"
     exit 0
 }
 
@@ -62,24 +63,29 @@ fi
 
 # parse username #
 studentName=$1
+studentTargetClassName=$2
 
 # check if the student account exist #
 # already done in s4usermove #
 
 # check if the account is a student #
-searchStudent=$(s4ldbsearch -H $samDatabase -b $baseStudentDN,$baseDN "(cn=$studentName)" | grep "dn: CN=$studentName,OU=.*,$baseStudentDN")
+searchStudent=$(s4ldbsearch -H $samDatabase -b $baseStudentDN,$baseDN "(cn=$studentName)" dn | grep "dn: CN=$studentName,OU=.*,$baseStudentDN")
 if [ -z "$searchStudent" ]; then
    echo "The user $studentName is not a student !"
    exit 0
 fi
 
-# check if the target class is a student's class #
-studentTargetClassName=$2
-studentTargetClassGroup=${2,,}
+# check if the class exist #
+if ! studentTargetClassInfo=$(s4classcheck $studentTargetClassName); then
+   echo "The student class $studentTargetClassName cannot be found !"
+   exit 0
+fi
 
-searchClass=$(s4ldbsearch -H $samDatabase -b $baseStudentDN,$baseDN "(cn=$studentTargetClassGroup)" | grep "dn: CN=$studentTargetClassGroup,OU=$studentTargetClassName,$baseStudentDN")
-if [ -z "$searchClass" ]; then
-   echo "The class $studentTargetClassName is not a student's class !"
+# check if the target class is a student's class #
+studentTargetClassDN=$(echo "$studentTargetClassInfo" | grep 'Class DN: ')
+studentTargetClassDN=${studentTargetClassDN#Class DN: }
+if ! echo "$studentTargetClassDN" | grep -q "$baseStudentDN\$"; then
+   echo "The student class $studentTargetClassName is not a student class !"
    exit 0
 fi
 
diff --git a/modules/samba/files/s4useradd b/modules/samba/files/s4useradd
--- a/modules/samba/files/s4useradd
+++ b/modules/samba/files/s4useradd
@@ -8,7 +8,8 @@ source /etc/samba/s4.conf
 # usage #
 function usage()
 {
-    echo "usage: $0 <user_name> [user_class] [-s server] [-p passwd]"
+    binName=$(basename $0)
+    echo "usage: $binName <user_name> [user_class] [-s server] [-p passwd]"
     exit 0
 }
 
@@ -84,20 +85,18 @@ fi
 if [ -z "$2" ]; then
    userClassName=${baseUserDN#OU=}
    userClassGroup=${baseUserGroup}
+   userClassDN=${baseUserDN}
 else
    userClassName=$2
-   userClassGroup=${2,,}
-fi
-
-
-# search the class #
-searchClass=$(s4ldbsearch -H $samDatabase -b $baseUserDN,$baseDN "(cn=$userClassGroup)" | grep "dn: CN=$userClassGroup,OU=$userClassName")
-if [ -z "$searchClass" ]; then
-   echo "The class $userClassName cannot be found !"
-   exit 0
-else
-   userClassDN=${searchClass#dn: CN=$userClassGroup,}
-   userClassDN=${userClassDN%,$baseDN}
+   if ! userClassInfo=$(s4classcheck $userClassName); then
+      echo "The class $userClassName cannot be found !"
+      exit 1
+   else
+      userClassGroup=$(echo "$userClassInfo" | grep 'Class group: ')
+      userClassGroup=${userClassGroup#Class group: }
+      userClassDN=$(echo "$userClassInfo" | grep 'Class DN: ')
+      userClassDN=${userClassDN#Class DN: }
+   fi
 fi
 
 
@@ -111,7 +110,6 @@ fi
 if [ -z "$userPasswd" ]; then
    userPasswd=$userName
 fi
-
 
 
 ###############################
