samba migrate scripts : added some optimizations

diff --git a/modules/samba/files/s4sharemigrate b/modules/samba/files/s4sharemigrate
--- a/modules/samba/files/s4sharemigrate
+++ b/modules/samba/files/s4sharemigrate
@@ -11,8 +11,10 @@ function usage()
     binName=$(basename $0)
     echo "usage: $binName [-n] [-l] <share_name> <target_server>"
     echo "       $binName [-n] [-l] -c <shares_class> <target_server>"
+    echo "       $binName [-n] -u"
     echo "   -n : non interractive"
     echo "   -l : migrate later"
+    echo "   -u : update all pending migrations now"
     exit 0
 }
 
@@ -25,7 +27,7 @@ while [[ -n "$@" ]]; do
 
     # test option #
     OPTIND=1
-    while getopts ":hnlc" opt; do
+    while getopts ":hnlcu" opt; do
 	case $opt in
             n)
                 optNoInterractive='true'
@@ -35,6 +37,9 @@ while [[ -n "$@" ]]; do
                 ;;
             c)
                 optBaseClass='true'
+                ;;
+            u)
+                optUpdatePending='true'
                 ;;
 	    h)
 		usage
@@ -78,17 +83,101 @@ function ask_yes_or_no() {
 # analyse args
 #################
 
-# need two args #
-if [ $# -ne 2 ]; then
-    usage
+# need two args, or none when just update #
+if [ "$optUpdatePending" != "true" ]; then
+   if [ $# -ne 2 ]; then
+      usage
+   fi
+else
+   if [ $# -ne 0 ]; then
+      usage
+   fi
+fi
+
+# the -u switch can't be used with -l or -c #
+if [ "$optUpdatePending" == "true" ]; then
+   if [ "$optLater" == "true" ] || [ "$optBaseClass" == "true" ]; then
+      usage
+   fi
+fi
+
+
+########################
+# server check library #
+########################
+
+# get hostname #
+hostname=$(hostname)
+
+# store checked servers #
+# contain tab separated : #
+# name local=true/false sharePath #
+migrationServers=''
+
+function checkServer() {
+
+   serverName="$1"
+
+   # ensure domain is removed #
+   serverName=$(echo "$serverName" | cut -d. -f1)
+
+   # check if the server is already checked #
+   if echo "$migrationServers" | grep -q "^$serverName[[:space:]]"; then
+      return
+   fi
+
+   # check if local #
+   if [ "$serverName" == "$hostname" ]; then
+      serverIsLocal='true'
+      serverSharePath="$unixSharePath"
+   else
+      serverIsLocal='false'
+
+      # check access to the server #
+      ssh -n $serverName -oBatchMode=yes 'echo hello' > /dev/null
+      if [ "$?" -ne "0" ]; then
+         echo "Cannot access to the server $serverName !"
+         echo "Please set a passwordless ssh connection with ssh-copy-id."
+         exit 1
+      fi
+
+      # get directories #
+      serverSharePath=$(ssh -n $serverName -oBatchMode=yes '. /etc/samba/s4.conf; echo $unixSharePath')
+      if [ "$?" -ne "0" ] || [ -z "$serverSharePath" ]; then
+         echo "Cannot find server $serverName share path !"
+         exit 1
+      fi
+
+   fi
+
+   # save #
+   if [ ! -z "$migrationServers" ]; then
+      migrationServers=$(echo -e "$migrationServers\n$serverName\t$serverIsLocal\t$serverSharePath")
+   else
+      migrationServers=$(echo -e "$serverName\t$serverIsLocal\t$serverSharePath")
+   fi
+}
+
+
+###############################
+# get target server and check #
+###############################
+if [ "$optUpdatePending" != "true" ]; then
+   targetServer="$2"
+   targetServer=$(echo "$targetServer" | cut -d. -f1)
+   checkServer "$targetServer"
 fi
 
 
 #############################################
-# check the shares than need to be migrated #
+# check the shares that need to be migrated #
 #############################################
+
+# will contain tab separated : #
+# dn cn sourceServer targetServer #
 migrateShares=''
 
+# BASE CLASS case #
 # if base class is given get all shares inside #
 if [ "$optBaseClass" == "true" ]; then
 
@@ -113,9 +202,9 @@ if [ "$optBaseClass" == "true" ]; then
    fi
 
    # display the result #
-   echo "--------------------------------------------------"
-   echo "The following shares will be migrated to $2 : "
-   echo "--------------------------------------------------"
+   echo "---------------------------------------------------------"
+   echo "The following shares will be migrated to $targetServer : "
+   echo "---------------------------------------------------------"
    while read -r migrateShareInfo; do
 
       # get the share class #
@@ -139,6 +228,54 @@ if [ "$optBaseClass" == "true" ]; then
       fi
    fi
 
+   # add target #
+   migrateShares=$(echo "$migrateShares" | sed "s/$/\t$targetServer/")
+
+# UPDATE case #
+# if we need to update, load and check the share list "
+elif [ "$optUpdatePending" == "true" ]; then
+
+   # check if we have shares to update #
+   pendingMigrationShareCount=$(grep -c -v '^ *$' $waitingFile)
+   if [ "$pendingMigrationShareCount" -eq "0" ]; then
+      echo "No pending share migration to update !"
+      exit 0
+   fi
+
+   # read the file before updating the content in case of error #
+   waitingShares=$(cat $waitingFile);
+
+   # check every waiting share #
+   while read pendingMigrationInfo; do
+
+      # get share and target #
+      pendingMigrationShare=$(echo "$pendingMigrationInfo" | cut -d ' ' -f1)
+      pendingMigrationServer=$(echo "$pendingMigrationInfo" | cut -d ' ' -f2)
+
+      # check share #
+      if ! pendingMigrationShareInfo=$(s4ldbsearch $baseShareDN,$baseDN sub user "(cn=$pendingMigrationShare)" cn unixHomeDirectory); then
+
+          # on error delete the share from the list #
+          # may the share don't exist anymore #
+          sed -i "/^\s*$pendingMigrationShare\s/d" "$waitingFile"
+
+      else
+
+         # check target server #
+         checkServer "$pendingMigrationServer"
+
+         # save share info with target #
+         if [ ! -z "$migrateShares" ]; then
+            migrateShares=$(echo -e "$migrateShares\n$pendingMigrationShareInfo\t$pendingMigrationServer")
+         else
+            migrateShares=$(echo -e "$pendingMigrationShareInfo\t$pendingMigrationServer")
+         fi
+      fi
+
+   done <<< "$waitingShares"
+
+
+# SINGLE SHARE case
 # if no class is given just one share to migrate #
 else
 
@@ -149,6 +286,9 @@ else
       echo "The share $migrateShareName does not exist !"
       exit 1
    fi
+
+   # add the target server #
+   migrateShares=$(echo -e "$migrateShares\t$targetServer")
 fi
 
 
@@ -175,69 +315,9 @@ if [ "$optNoInterractive" != "true" ] && [ "$optLater" != "true" ]; then
 fi
 
 
-##################################
-# get target server and hostname #
-##################################
-targetServer="$2"
-targetServer=$(echo "$targetServer" | cut -d. -f1)
-hostname=$(hostname)
-
-
-#####################
-# check all servers #
-#####################
-
-# store checked servers #
-migrationServers=''
-
-# add : name,local=true/false,sharePath #
-# to migrationServers                   #
-function checkServer() {
-
-   serverName="$1"
-
-   # ensure domain is removed #
-   serverName=$(echo "$serverName" | cut -d. -f1)
-
-   # check if the server is already checked #
-   if echo -e "$migrationServers" | grep -q "^$serverName[[:space:]]"; then
-      return
-   fi
-
-   # check if local #
-   if [ "$serverName" == "$hostname" ]; then
-      serverIsLocal='true'
-      serverSharePath="$unixSharePath"
-   else
-      serverIsLocal='false'
-
-      # check access to the server #
-      ssh -n $serverName -oBatchMode=yes 'echo hello' > /dev/null
-      if [ "$?" -ne "0" ]; then
-         echo "Cannot access to the server $serverName !"
-         echo "Please set a passwordless ssh connection with ssh-copy-id."
-         exit 1
-      fi
-
-      # get share path #
-      serverSharePath=$(ssh -n $serverName -oBatchMode=yes '. /etc/samba/s4.conf; echo $unixSharePath')
-      if [ "$?" -ne "0" ] || [ -z "$serverSharePath" ]; then
-         echo "Cannot find server $serverName share path !"
-         exit 1
-      fi
-   fi
-
-   # save #
-   if [ ! -z "$migrationServers" ]; then
-      migrationServers="$migrationServers\n"
-   fi
-   migrationServers="$migrationServers$serverName\t$serverIsLocal\t$serverSharePath"
-}
-
-# check target server #
-checkServer "$targetServer"
-
+############################
 # check all source servers #
+############################
 while read -r migrateShareInfo; do
 
    # get source server #
@@ -262,22 +342,6 @@ done <<< "$migrateShares";
 #                          #
 #--------------------------#
 
-# get target server info #
-targetServerInfo=$(echo -e "$migrationServers" | grep "^$targetServer[[:space:]]")
-if [ "$?" -ne "0" ]; then
-   echo "Failed to get target server $targetServer information !"
-   exit 1
-fi
-
-targetServerIsLocal=$(echo "$targetServerInfo" | cut -f2)
-targetServerSharePath=$(echo "$targetServerInfo" | cut -f3)
-
-# sanitary check #
-if [ -z "$targetServerIsLocal" ] || [ -z "$targetServerSharePath" ]; then
-   echo "Failed to get target server $targetServer information !"
-   exit 1
-fi
-
 
 ######################
 # migrate all shares #
@@ -288,6 +352,7 @@ while read -r migrateShareInfo; do
    shareDN=$(echo "$migrateShareInfo" | cut -f1)
    shareName=$(echo "$migrateShareInfo" | cut -f2)
    sourceServer=$(echo "$migrateShareInfo" | cut -f3)
+   targetServer=$(echo "$migrateShareInfo" | cut -f4)
 
    # check if we need to migrate #
    if [ "$targetServer" == "$sourceServer" ]; then
@@ -312,7 +377,7 @@ while read -r migrateShareInfo; do
    fi
 
    # get source server info #
-   sourceServerInfo=$(echo -e "$migrationServers" | grep "^$sourceServer[[:space:]]")
+   sourceServerInfo=$(echo "$migrationServers" | grep "^$sourceServer[[:space:]]")
    if [ "$?" -ne "0" ]; then
       echo "Failed to get source server $sourceServer information !"
       exit 1
@@ -324,6 +389,23 @@ while read -r migrateShareInfo; do
    # sanitary check #
    if [ -z "$sourceServerIsLocal" ] || [ -z "$sourceServerSharePath" ]; then
       echo "Failed to get source server $sourceServer information !"
+      exit 1
+   fi
+
+
+   # get target server info #
+   targetServerInfo=$(echo "$migrationServers" | grep "^$targetServer[[:space:]]")
+   if [ "$?" -ne "0" ]; then
+      echo "Failed to get target server $targetServer information !"
+      exit 1
+   fi
+
+   targetServerIsLocal=$(echo "$targetServerInfo" | cut -f2)
+   targetServerSharePath=$(echo "$targetServerInfo" | cut -f3)
+
+   # sanitary check #
+   if [ -z "$targetServerIsLocal" ] || [ -z "$targetServerSharePath" ]; then
+      echo "Failed to get target server $targetServer information !"
       exit 1
    fi
 
@@ -372,19 +454,19 @@ while read -r migrateShareInfo; do
    fi
 
 
-   ###################
-   # rsync to target #
-   ###################
-   shareMigrated=''
+   #########################
+   # rsync share to target #
+   #########################
+   shareDirectoryMigrated=''
 
-   # check if share directory exits #
+   # check if directory exits #
    if [ "$sourceServerIsLocal" == 'true' ]; then
       test -e "$sourceServerSharePath/$shareName"
    else
       ssh -n $sourceServer -oBatchMode=yes "test -e $sourceServerSharePath/$shareName"
    fi
 
-   # rsync if exist #
+   # rsync directory if exist #
    if [ "$?" -eq "0" ]; then
 
       # build source #
@@ -402,13 +484,13 @@ while read -r migrateShareInfo; do
       fi
 
       # rsync #
-      echo "Migrating $shareName to $targetServer..."
+      echo "Migrating $shareName directory to $targetServer..."
       rsync -XAaz --delete-after $rsyncSource $rsyncDest
       if [ "$?" -eq '0' ]; then
-         echo "Share $shareName migrated to $targetServer."
-         shareMigrated='true'
+         echo "Share $shareName directory migrated to $targetServer."
+         shareDirectoryMigrated='true'
       else
-         echo "Error while migrating $shareName to $targetServer !"
+         echo "Error while migrating $shareName directory to $targetServer !"
          exit 1
       fi
    else
@@ -416,14 +498,14 @@ while read -r migrateShareInfo; do
    fi
 
 
-   ################
-   # update share #
-   ################
+   ##################
+   # update account #
+   ##################
 
    echo "dn: $shareDN
 changetype: modify
 replace: unixHomeDirectory
-unixHomeDirectory: $targetServer" > /tmp/$shareName
+unixHomeDirectory: ${targetServer}" > /tmp/$shareName
 
    ldbmodify --url=$samDatabase -b $baseDN /tmp/$shareName
    rm /tmp/$shareName
@@ -439,7 +521,7 @@ unixHomeDirectory: $targetServer" > /tmp/$shareName
    ################
    # clean source #
    ################
-   if [ "$shareMigrated" == 'true' ]; then
+   if [ "$shareDirectoryMigrated" == 'true' ]; then
 
       # remove source #
       if [ "$sourceServerIsLocal" == 'true' ]; then
diff --git a/modules/samba/files/s4usermigrate b/modules/samba/files/s4usermigrate
--- a/modules/samba/files/s4usermigrate
+++ b/modules/samba/files/s4usermigrate
@@ -11,8 +11,10 @@ function usage()
     binName=$(basename $0)
     echo "usage: $binName [-n] [-l] <user_name> <target_server>"
     echo "       $binName [-n] [-l] -c <users_class> <target_server>"
+    echo "       $binName [-n] -u"
     echo "   -n : non interractive"
     echo "   -l : migrate later"
+    echo "   -u : update all pending migrations now"
     exit 0
 }
 
@@ -25,7 +27,7 @@ while [[ -n "$@" ]]; do
 
     # test option #
     OPTIND=1
-    while getopts ":hnlc" opt; do
+    while getopts ":hnlcu" opt; do
 	case $opt in
             n)
                 optNoInterractive='true'
@@ -35,6 +37,9 @@ while [[ -n "$@" ]]; do
                 ;;
             c)
                 optBaseClass='true'
+                ;;
+            u)
+                optUpdatePending='true'
                 ;;
 	    h)
 		usage
@@ -78,120 +83,37 @@ function ask_yes_or_no() {
 # analyse args
 #################
 
-# need two args #
-if [ $# -ne 2 ]; then
-    usage
-fi
-
-
-############################################
-# check the users than need to be migrated #
-############################################
-migrateUsers=''
-
-# if base class is given get all users inside #
-if [ "$optBaseClass" == "true" ]; then
-
-   baseClass="$1"
-
-   # check the class #
-   if ! baseClassInfo=$(s4classcheck $baseClass); then
-      echo "The class $baseClass cannot be found !"
-      exit 1
-   else
-      baseClassDN=$(echo "$baseClassInfo" | grep 'Class DN: ')
-      baseClassDN=${baseClassDN#Class DN: }
+# need two args, or none when just update #
+if [ "$optUpdatePending" != "true" ]; then
+   if [ $# -ne 2 ]; then
+      usage
    fi
-
-   # get all the users #
-   migrateUsers=$(s4ldbsearch $baseClassDN,$baseDN sub user '()' cn unixHomeDirectory)
-
-   # check if we have users #
-   if [ -z "$migrateUsers" ]; then
-      echo "No users in class $baseClass."
-      exit 0
-   fi
-
-   # display the result #
-   echo "--------------------------------------------------"
-   echo "The following users will be migrated to $2 : "
-   echo "--------------------------------------------------"
-   while read -r migrateUserInfo; do
-
-      # get the user class #
-      migrateUserClass=$(echo "$migrateUserInfo" | cut -f1)
-      migrateUserClass=$(echo "$migrateUserClass" | cut -d ',' -f2)
-      migrateUserClass=${migrateUserClass#OU=}
-
-      # get the user name #
-      migrateUserName=$(echo "$migrateUserInfo" | cut -f2)
-
-      # display #
-      echo "User $migrateUserName from class $migrateUserClass"
-
-   done <<< "$migrateUsers"
-   echo "--------------------------------------------------"
-
-   # if needed ask to continue #
-   if [ "$optNoInterractive" != "true" ]; then
-      if [ $(ask_yes_or_no "Do you want to continue ?") == "no" ]; then
-         exit 0
-      fi
-   fi
-
-# if no class is given just one user to migrate #
 else
+   if [ $# -ne 0 ]; then
+      usage
+   fi
+fi
 
-   migrateUserName="$1"
-
-   # check if the user exist #
-   if ! migrateUsers=$(s4ldbsearch $baseUserDN,$baseDN sub user "(cn=$migrateUserName)" cn unixHomeDirectory); then
-      echo "The user $migrateUserName does not exist !"
-      exit 1
+# the -u switch can't be used with -l or -c #
+if [ "$optUpdatePending" == "true" ]; then
+   if [ "$optLater" == "true" ] || [ "$optBaseClass" == "true" ]; then
+      usage
    fi
 fi
 
 
-##############
-# check time #
-##############
-if [ "$optNoInterractive" != "true" ] && [ "$optLater" != "true" ]; then
+########################
+# server check library #
+########################
 
-   # get current time #
-   currentTime=$(date +%H%M | sed 's/^0*//');
-
-   # check time #
-   # warning between 5:00 and 21:00 #
-   if [ "$currentTime" -gt "500" ] && [ "$currentTime" -lt "2100" ]; then
-      echo "----------------------------------------------------------------"
-      echo "WARNING : you are about to migrate users !"
-      echo "You need to be sure that the users are not currently logged !"
-      echo "You can use the -l option to migrate the user later by cron job."
-      echo "----------------------------------------------------------------"
-      if [ $(ask_yes_or_no "Are you sure you want to continue ?") == "no" ]; then
-         exit 0
-      fi
-   fi
-fi
-
-
-##################################
-# get target server and hostname #
-##################################
-targetServer="$2"
-targetServer=$(echo "$targetServer" | cut -d. -f1)
+# get hostname #
 hostname=$(hostname)
 
-
-#####################
-# check all servers #
-#####################
-
 # store checked servers #
+# contain tab separated : #
+# name local=true/false homePath profilePath #
 migrationServers=''
 
-# add : name,local=true/false,homePath,profilePath #
-# to migrationServers                              #
 function checkServer() {
 
    serverName="$1"
@@ -200,7 +122,7 @@ function checkServer() {
    serverName=$(echo "$serverName" | cut -d. -f1)
 
    # check if the server is already checked #
-   if echo -e "$migrationServers" | grep -q "^$serverName[[:space:]]"; then
+   if echo "$migrationServers" | grep -q "^$serverName[[:space:]]"; then
       return
    fi
 
@@ -236,15 +158,172 @@ function checkServer() {
 
    # save #
    if [ ! -z "$migrationServers" ]; then
-      migrationServers="$migrationServers\n"
+      migrationServers=$(echo -e "$migrationServers\n$serverName\t$serverIsLocal\t$serverHomePath\t$serverProfilePath")
+   else
+      migrationServers=$(echo -e "$serverName\t$serverIsLocal\t$serverHomePath\t$serverProfilePath")
    fi
-   migrationServers="$migrationServers$serverName\t$serverIsLocal\t$serverHomePath\t$serverProfilePath"
 }
 
-# check target server #
-checkServer "$targetServer"
 
+###############################
+# get target server and check #
+###############################
+if [ "$optUpdatePending" != "true" ]; then
+   targetServer="$2"
+   targetServer=$(echo "$targetServer" | cut -d. -f1)
+   checkServer "$targetServer"
+fi
+
+
+############################################
+# check the users that need to be migrated #
+############################################
+
+# will contain tab separated : #
+# dn cn unixHomeDirectory targetServer #
+migrateUsers=''
+
+# BASE CLASS case #
+# if base class is given get all users inside #
+if [ "$optBaseClass" == "true" ]; then
+
+   baseClass="$1"
+
+   # check the class #
+   if ! baseClassInfo=$(s4classcheck $baseClass); then
+      echo "The class $baseClass cannot be found !"
+      exit 1
+   else
+      baseClassDN=$(echo "$baseClassInfo" | grep 'Class DN: ')
+      baseClassDN=${baseClassDN#Class DN: }
+   fi
+
+   # get all the users #
+   migrateUsers=$(s4ldbsearch $baseClassDN,$baseDN sub user '()' cn unixHomeDirectory)
+
+   # check if we have users #
+   if [ -z "$migrateUsers" ]; then
+      echo "No users in class $baseClass."
+      exit 0
+   fi
+
+   # display the result #
+   echo "--------------------------------------------------------"
+   echo "The following users will be migrated to $targetServer : "
+   echo "--------------------------------------------------------"
+   while read -r migrateUserInfo; do
+
+      # get the user class #
+      migrateUserClass=$(echo "$migrateUserInfo" | cut -f1)
+      migrateUserClass=$(echo "$migrateUserClass" | cut -d ',' -f2)
+      migrateUserClass=${migrateUserClass#OU=}
+
+      # get the user name #
+      migrateUserName=$(echo "$migrateUserInfo" | cut -f2)
+
+      # display #
+      echo "User $migrateUserName from class $migrateUserClass"
+
+   done <<< "$migrateUsers"
+   echo "--------------------------------------------------"
+
+   # if needed ask to continue #
+   if [ "$optNoInterractive" != "true" ]; then
+      if [ $(ask_yes_or_no "Do you want to continue ?") == "no" ]; then
+         exit 0
+      fi
+   fi
+
+   # add target #
+   migrateUsers=$(echo "$migrateUsers" | sed "s/$/\t$targetServer/")
+
+# UPDATE case #
+# if we need to update, load and check the user list "
+elif [ "$optUpdatePending" == "true" ]; then
+
+   # check if we have users to update #
+   pendingMigrationUserCount=$(grep -c -v '^ *$' $waitingFile)
+   if [ "$pendingMigrationUserCount" -eq "0" ]; then
+      echo "No pending user migration to update !"
+      exit 0
+   fi
+
+   # read the file before updating the content in case of error #
+   waitingUsers=$(cat $waitingFile);
+
+   # check every waiting user #
+   while read pendingMigrationInfo; do
+
+      # get user and target #
+      pendingMigrationUser=$(echo "$pendingMigrationInfo" | cut -d ' ' -f1)
+      pendingMigrationServer=$(echo "$pendingMigrationInfo" | cut -d ' ' -f2)
+
+      # check user #
+      if ! pendingMigrationUserInfo=$(s4ldbsearch $baseUserDN,$baseDN sub user "(cn=$pendingMigrationUser)" cn unixHomeDirectory); then
+
+          # on error delete the user from the list #
+          # may the user don't exist anymore #
+          sed -i "/^\s*$pendingMigrationUser\s/d" "$waitingFile"
+
+      else
+
+         # check target server #
+         checkServer "$pendingMigrationServer"
+
+         # save user info with target #
+         if [ ! -z "$migrateUsers" ]; then
+            migrateUsers=$(echo -e "$migrateUsers\n$pendingMigrationUserInfo\t$pendingMigrationServer")
+         else
+            migrateUsers=$(echo -e "$pendingMigrationUserInfo\t$pendingMigrationServer")
+         fi
+      fi
+
+   done <<< "$waitingUsers"
+
+
+# SINGLE USER case
+# if no class is given just one user to migrate #
+else
+
+   migrateUserName="$1"
+
+   # check if the user exist #
+   if ! migrateUsers=$(s4ldbsearch $baseUserDN,$baseDN sub user "(cn=$migrateUserName)" cn unixHomeDirectory); then
+      echo "The user $migrateUserName does not exist !"
+      exit 1
+   fi
+
+   # add the target server #
+   migrateUsers=$(echo -e "$migrateUsers\t$targetServer")
+fi
+
+
+##############
+# check time #
+##############
+if [ "$optNoInterractive" != "true" ] && [ "$optLater" != "true" ]; then
+
+   # get current time #
+   currentTime=$(date +%H%M | sed 's/^0*//');
+
+   # check time #
+   # warning between 5:00 and 21:00 #
+   if [ "$currentTime" -gt "500" ] && [ "$currentTime" -lt "2100" ]; then
+      echo "----------------------------------------------------------------"
+      echo "WARNING : you are about to migrate users !"
+      echo "You need to be sure that the users are not currently logged !"
+      echo "You can use the -l option to migrate the user later by cron job."
+      echo "----------------------------------------------------------------"
+      if [ $(ask_yes_or_no "Are you sure you want to continue ?") == "no" ]; then
+         exit 0
+      fi
+   fi
+fi
+
+
+############################
 # check all source servers #
+############################
 while read -r migrateUserInfo; do
 
    # get source server #
@@ -271,23 +350,6 @@ done <<< "$migrateUsers";
 #                          #
 #--------------------------#
 
-# get target server info #
-targetServerInfo=$(echo -e "$migrationServers" | grep "^$targetServer[[:space:]]")
-if [ "$?" -ne "0" ]; then
-   echo "Failed to get target server $targetServer information !"
-   exit 1
-fi
-
-targetServerIsLocal=$(echo "$targetServerInfo" | cut -f2)
-targetServerHomePath=$(echo "$targetServerInfo" | cut -f3)
-targetServerProfilePath=$(echo "$targetServerInfo" | cut -f4)
-
-# sanitary check #
-if [ -z "$targetServerIsLocal" ] || [ -z "$targetServerHomePath" ] || [ -z "$targetServerProfilePath" ]; then
-   echo "Failed to get target server $targetServer information !"
-   exit 1
-fi
-
 
 #####################
 # migrate all users #
@@ -300,6 +362,7 @@ while read -r migrateUserInfo; do
    sourceServer=$(echo "$migrateUserInfo" | cut -f3)
    sourceServer=${sourceServer#/dnfs/$homeShare/}
    sourceServer=$(echo "$sourceServer" | cut -d'/' -f1)
+   targetServer=$(echo "$migrateUserInfo" | cut -f4)
 
    # check if we need to migrate #
    if [ "$targetServer" == "$sourceServer" ]; then
@@ -324,7 +387,7 @@ while read -r migrateUserInfo; do
    fi
 
    # get source server info #
-   sourceServerInfo=$(echo -e "$migrationServers" | grep "^$sourceServer[[:space:]]")
+   sourceServerInfo=$(echo "$migrationServers" | grep "^$sourceServer[[:space:]]")
    if [ "$?" -ne "0" ]; then
       echo "Failed to get source server $sourceServer information !"
       exit 1
@@ -337,6 +400,24 @@ while read -r migrateUserInfo; do
    # sanitary check #
    if [ -z "$sourceServerIsLocal" ] || [ -z "$sourceServerHomePath" ] || [ -z "$sourceServerProfilePath" ]; then
       echo "Failed to get source server $sourceServer information !"
+      exit 1
+   fi
+
+
+   # get target server info #
+   targetServerInfo=$(echo "$migrationServers" | grep "^$targetServer[[:space:]]")
+   if [ "$?" -ne "0" ]; then
+      echo "Failed to get target server $targetServer information !"
+      exit 1
+   fi
+
+   targetServerIsLocal=$(echo "$targetServerInfo" | cut -f2)
+   targetServerHomePath=$(echo "$targetServerInfo" | cut -f3)
+   targetServerProfilePath=$(echo "$targetServerInfo" | cut -f4)
+
+   # sanitary check #
+   if [ -z "$targetServerIsLocal" ] || [ -z "$targetServerHomePath" ] || [ -z "$targetServerProfilePath" ]; then
+      echo "Failed to get target server $targetServer information !"
       exit 1
    fi
 
